server {
    listen 80;
    server_name 47.128.217.200 localhost;
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass container-dinamis:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Blok akses langsung ke folder src
    location ~ /src/ {
        deny all;
    }
}
