name: Deploy Dynamic App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "sitimalikha19" --password-stdin
          docker build -t sitimalikha19/kerudung-app:latest -f Dockerfile.txt .
          docker push sitimalikha19/kerudung-app:latest